spring:
  application:
    name: zuul
  rabbitmq: 
    host: 192.168.64.5
    port: 5672
    username: admin
    password: admin 
        
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka1:2002/eureka

#zuul 路由配置可以省略，缺省以服务 id 作为访问路径
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
zuul:   
  retryable: true
  
#ribbon:
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1  #默认配置
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream            
            
    
    